### ISSUE TITLE
Bro implemennt rss for this app

### ISSUE THREAD

**Issue by TouchstoneTheDev** [EVIL-ACID/Cyber-news#1]
i have about a thousend rss feeds! tell me if you are intrested fetching will be simple like you app  will be aggregator of the feeds

**Comment by oomar100** [comment]
I haven't touched this in a while lol and I don't think I'll have any time for it in the future but thanks for the idea tho, if I decide to add some features to it in the future I'll definitely add ur suggestion 👍 .
